import { Post } from '../interfaces/post.interface'
import { categories } from './category.db'

export const posts: Post[] = [
  {
    id: 1,
    title: 'Introduction to Angular',
    text: 'Learn the basics of Angular and how to get started with this powerful framework. Angular is a platform for building mobile and desktop web applications. It provides a way to structure your application and build reusable components. This guide will walk you through the essential concepts and help you set up your first Angular project.',
    imageUrl:
      'https://media2.dev.to/dynamic/image/width=1600,height=900,fit=cover,gravity=auto,format=auto/https%3A%2F%2Fdev-to-uploads.s3.amazonaws.com%2Fuploads%2Farticles%2Fm1jq1pmo3inn73mw30bj.png',
    category: categories.find((category) => category.id === 1)!,
    publicationDate: '2023-01-15',
  },
  {
    id: 2,
    title: 'Top 10 JavaScript Tips',
    text: 'Discover the top 10 tips to improve your JavaScript coding skills. JavaScript is a versatile language, and mastering it requires understanding its quirks and best practices. This article covers tips such as avoiding global variables, using strict mode, leveraging modern ES6+ features, and optimizing performance for better user experiences.',
    imageUrl:
      'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRID8qk3Qv5XsskZW6BMI1aeivnzCt0G5fWxQ&s',
    category: categories.find((category) => category.id === 2)!,
    publicationDate: '2023-02-10',
  },
  {
    id: 3,
    title: 'Understanding TypeScript',
    text: 'A comprehensive guide to understanding and using TypeScript in your projects. TypeScript is a superset of JavaScript that adds static typing, making it easier to catch errors during development. This guide explains the benefits of TypeScript, how to set it up, and how to use advanced features like generics, decorators, and type inference.',
    imageUrl: 'https://img-c.udemycdn.com/course/750x422/947098_02ec_2.jpg',
    category: categories.find((category) => category.id === 4)!,
    publicationDate: '2023-03-05',
  },
  {
    id: 4,
    title: 'Building Responsive Websites',
    text: 'Learn how to create responsive websites using modern CSS techniques. Responsive design ensures that your website looks great on all devices, from desktops to smartphones. This article covers CSS Grid, Flexbox, media queries, and other techniques to build layouts that adapt seamlessly to different screen sizes.',
    imageUrl:
      'https://miro.medium.com/v2/resize:fit:2000/1*qF8LfAwUhl57g9T0BVvVdg.jpeg',
    category: categories.find((category) => category.id === 3)!,
    publicationDate: '2023-04-12',
  },
  {
    id: 5,
    title: 'Advanced TypeScript Patterns',
    text: 'Explore advanced patterns and techniques in TypeScript for scalable applications. This article dives into advanced concepts like utility types, conditional types, mapped types, and how to use them to create robust and maintainable codebases. Learn how to leverage TypeScript to its full potential in large-scale projects.',
    imageUrl:
      'https://repository-images.githubusercontent.com/545397149/91a3b1e0-a4ec-478e-9342-825eb69faea4',
    category: categories.find((category) => category.id === 4)!,
    publicationDate: '2023-05-20',
  },
  {
    id: 6,
    title: 'JavaScript Frameworks Comparison',
    text: 'A detailed comparison of popular JavaScript frameworks like React, Angular, and Vue. Each framework has its strengths and weaknesses, and this article provides an in-depth analysis of their features, performance, community support, and use cases to help you choose the right one for your project.',
    imageUrl:
      'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQbS60LCmeVWQaKUM-qDtyUE8zwvtQKTZ0dZA&s',
    category: categories.find((category) => category.id === 2)!,
    publicationDate: '2023-06-15',
  },
  {
    id: 7,
    title: 'Mastering CSS Animations',
    text: 'CSS animations can bring life to your web applications. This guide covers everything from basic transitions to complex keyframe animations. Learn how to create smooth, performant animations that enhance user experience without compromising performance.',
    imageUrl: 'https://i.ytimg.com/vi/2D32OZ7S3ls/maxresdefault.jpg',
    category: categories.find((category) => category.id === 3)!,
    publicationDate: '2023-07-10',
  },
  {
    id: 8,
    title: 'Node.js Performance Optimization',
    text: 'Node.js is a powerful runtime for building server-side applications. This article explores techniques to optimize Node.js performance, including event loop management, asynchronous programming, and memory profiling. Learn how to build fast and efficient Node.js applications.',
    imageUrl:
      'https://miro.medium.com/v2/resize:fit:758/1*Rm5MQnXBIIWvu3V-wlEHCA.png',
    category: categories.find((category) => category.id === 5)!,
    publicationDate: '2023-08-01',
  },
  {
    id: 9,
    title: 'Introduction to WebAssembly',
    text: 'WebAssembly (Wasm) is a binary instruction format that allows high-performance applications to run on the web. This article introduces WebAssembly, its use cases, and how to integrate it into your web projects. Learn how to unlock new possibilities with WebAssembly.',
    imageUrl:
      'https://miro.medium.com/v2/resize:fit:1016/1*fXdFlcYYGAPJtviyingAdA.png',
    category: categories.find((category) => category.id === 6)!,
    publicationDate: '2023-09-15',
  },
  {
    id: 10,
    title: 'Getting Started with GraphQL',
    text: 'GraphQL is a query language for APIs that provides a more efficient and flexible alternative to REST. This guide explains the basics of GraphQL, how to set up a GraphQL server, and how to query data using GraphQL. Learn how to build modern APIs with GraphQL.',
    imageUrl: 'https://graphql.org/img/logo.svg',
    category: categories.find((category) => category.id === 7)!,
    publicationDate: '2023-10-05',
  },
  {
    id: 11,
    title: 'Introduction to Docker',
    text: 'Learn how to containerize your applications using Docker. This guide covers the basics of Docker, creating Dockerfiles, and managing containers.',
    imageUrl:
      'https://miro.medium.com/v2/resize:fit:1400/1*y6CvfE6WUgoIdT8Mp0Ev_g.png',
    category: categories.find((category) => category.id === 8)!,
    publicationDate: '2023-10-15',
  },
  {
    id: 12,
    title: 'Kubernetes for Beginners',
    text: 'An introduction to Kubernetes, the popular container orchestration platform. Learn how to deploy, scale, and manage containerized applications.',
    imageUrl:
      'https://i.ytimg.com/vi/TRebQVK_eo8/hq720.jpg?sqp=-oaymwEhCK4FEIIDSFryq4qpAxMIARUAAAAAGAElAADIQj0AgKJD&rs=AOn4CLDEq-su1H_mwHpiwUJ84USsRZ1dYw',
    category: categories.find((category) => category.id === 8)!,
    publicationDate: '2023-10-20',
  },
  {
    id: 13,
    title: 'Building REST APIs with Express.js',
    text: 'Learn how to build RESTful APIs using Express.js, a minimal and flexible Node.js web application framework.',
    imageUrl:
      'https://bs-uploads.toptal.io/blackfish-uploads/components/blog_post_page/4085508/cover_image/retina_1708x683/cover-secure-rest-api-in-nodejs-b92e70bf49831319301978b399444568.png',
    category: categories.find((category) => category.id === 5)!,
    publicationDate: '2023-11-01',
  },
  {
    id: 14,
    title: 'Introduction to Machine Learning',
    text: 'A beginner-friendly guide to understanding the basics of machine learning and its applications.',
    imageUrl: 'https://miro.medium.com/max/1400/1*Z6a6l9Z2b8Y9J2kV8xM9Wg.png',
    category: categories.find((category) => category.id === 9)!,
    publicationDate: '2023-11-10',
  },
  {
    id: 15,
    title: 'Python for Data Science',
    text: 'Learn how to use Python for data analysis, visualization, and machine learning.',
    imageUrl: 'https://www.python.org/static/community_logos/python-logo.png',
    category: categories.find((category) => category.id === 9)!,
    publicationDate: '2023-11-15',
  },
  {
    id: 16,
    title: 'Introduction to DevOps',
    text: 'Understand the principles of DevOps and how it bridges the gap between development and operations.',
    imageUrl: 'https://miro.medium.com/max/1400/1*oJZ8zG8Xz5Fq4Z1z7e1V9g.png',
    category: categories.find((category) => category.id === 10)!,
    publicationDate: '2023-11-20',
  },
  {
    id: 17,
    title: 'React State Management',
    text: 'Explore state management techniques in React, including Context API, Redux, and Zustand.',
    imageUrl: 'https://reactjs.org/logo-og.png',
    category: categories.find((category) => category.id === 2)!,
    publicationDate: '2023-11-25',
  },
  {
    id: 18,
    title: 'Introduction to Next.js',
    text: 'Learn how to build server-side rendered React applications using Next.js.',
    imageUrl: 'https://nextjs.org/static/twitter-cards/home.jpg',
    category: categories.find((category) => category.id === 2)!,
    publicationDate: '2023-12-01',
  },
  {
    id: 19,
    title: 'GraphQL vs REST',
    text: 'A comparison of GraphQL and REST APIs to help you choose the right approach for your project.',
    imageUrl: 'https://graphql.org/img/logo.svg',
    category: categories.find((category) => category.id === 7)!,
    publicationDate: '2023-12-05',
  },
  {
    id: 20,
    title: 'Introduction to Web Security',
    text: 'Learn the basics of web security, including common vulnerabilities and how to protect your applications.',
    imageUrl: 'https://owasp.org/assets/images/logo.png',
    category: categories.find((category) => category.id === 11)!,
    publicationDate: '2023-12-10',
  },
  {
    id: 21,
    title: 'Building Microservices with Spring Boot',
    text: 'Learn how to build scalable microservices using Spring Boot and Spring Cloud.',
    imageUrl: 'https://spring.io/images/spring-logo-2022-2.png',
    category: categories.find((category) => category.id === 12)!,
    publicationDate: '2023-12-15',
  },
  {
    id: 22,
    title: 'Introduction to Artificial Intelligence',
    text: 'A beginner-friendly guide to understanding artificial intelligence and its applications.',
    imageUrl: 'https://miro.medium.com/max/1400/1*Z6a6l9Z2b8Y9J2kV8xM9Wg.png',
    category: categories.find((category) => category.id === 9)!,
    publicationDate: '2023-12-20',
  },
  {
    id: 23,
    title: 'Building Progressive Web Apps',
    text: 'Learn how to create Progressive Web Apps (PWAs) that work offline and provide a native app-like experience.',
    imageUrl: 'https://web.dev/images/pwa.svg',
    category: categories.find((category) => category.id === 13)!,
    publicationDate: '2023-12-25',
  },
  {
    id: 24,
    title: 'Introduction to Blockchain',
    text: 'Understand the basics of blockchain technology and its use cases.',
    imageUrl: 'https://miro.medium.com/max/1400/1*Z6a6l9Z2b8Y9J2kV8xM9Wg.png',
    category: categories.find((category) => category.id === 14)!,
    publicationDate: '2023-12-30',
  },
  {
    id: 25,
    title: 'Introduction to Cloud Computing',
    text: 'Learn the fundamentals of cloud computing and popular cloud platforms like AWS, Azure, and Google Cloud.',
    imageUrl: 'https://miro.medium.com/max/1400/1*Z6a6l9Z2b8Y9J2kV8xM9Wg.png',
    category: categories.find((category) => category.id === 15)!,
    publicationDate: '2024-01-05',
  },
  {
    id: 26,
    title: 'Building Serverless Applications',
    text: 'Learn how to build serverless applications using AWS Lambda and other serverless platforms.',
    imageUrl: 'https://miro.medium.com/max/1400/1*Z6a6l9Z2b8Y9J2kV8xM9Wg.png',
    category: categories.find((category) => category.id === 15)!,
    publicationDate: '2024-01-10',
  },
  {
    id: 27,
    title: 'Introduction to Data Structures',
    text: 'Understand the basics of data structures and their importance in computer science.',
    imageUrl: 'https://miro.medium.com/max/1400/1*Z6a6l9Z2b8Y9J2kV8xM9Wg.png',
    category: categories.find((category) => category.id === 16)!,
    publicationDate: '2024-01-15',
  },
  {
    id: 28,
    title: 'Introduction to Algorithms',
    text: 'Learn the basics of algorithms and how to solve problems efficiently.',
    imageUrl: 'https://miro.medium.com/max/1400/1*Z6a6l9Z2b8Y9J2kV8xM9Wg.png',
    category: categories.find((category) => category.id === 16)!,
    publicationDate: '2024-01-20',
  },
  {
    id: 29,
    title: 'Introduction to Functional Programming',
    text: 'Learn the principles of functional programming and how to apply them in JavaScript.',
    imageUrl: 'https://miro.medium.com/max/1400/1*Z6a6l9Z2b8Y9J2kV8xM9Wg.png',
    category: categories.find((category) => category.id === 17)!,
    publicationDate: '2024-01-25',
  },
  {
    id: 30,
    title: 'Introduction to Web Performance Optimization',
    text: 'Learn how to optimize the performance of your web applications.',
    imageUrl: 'https://miro.medium.com/max/1400/1*Z6a6l9Z2b8Y9J2kV8xM9Wg.png',
    category: categories.find((category) => category.id === 18)!,
    publicationDate: '2024-01-30',
  },
]
